// Çok dilli içerik: meal/sahibi {tr, en, de, ar, ku}
export const AYETLER = [
  { id: 1, sure: 'Bakara', ayet: '153',
    arapca: 'يَا أَيُّهَا الَّذِينَ آمَنُوا اسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ ۚ إِنَّ اللَّهَ مَعَ الصَّابِرِينَ',
    meal: { tr: 'Ey iman edenler! Sabır ve namazla Allah’tan yardım isteyin. Şüphesiz Allah sabredenlerle beraberdir.', en: 'O you who believe! Seek help through patience and prayer. Indeed, Allah is with the patient.', de: 'O ihr Gläubigen! Sucht Hilfe in Geduld und Gebet. Wahrlich, Allah ist mit den Geduldigen.', ar: 'يا أيها الذين آمنوا استعينوا بالصبر والصلاة إن الله مع الصابرين.', ku: 'Gelo hûn bawerî anîn! Bi hewq û nimêjê ji Xwedê alîkarî bixwazin. Bêguman Xwedê bi hewqkeran re ye.' } },
  { id: 2, sure: 'İhlas', ayet: '1-4',
    arapca: 'قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ',
    meal: { tr: 'De ki: O Allah’tır, tektir. Allah Samed’dir. Doğurmamıştır ve doğmamıştır. Hiç kimse O’na denk değildir.', en: 'Say: He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born. None is comparable to Him.', de: 'Sprich: Er ist Allah, ein Einziger. Allah, der Ewige. Er zeugt nicht und wurde nicht gezeugt. Niemand ist Ihm gleich.', ar: 'قل هو الله أحد، الله الصمد، لم يلد ولم يولد، ولم يكن له كفواً أحد.', ku: 'Bêje: Ew Xwedê yek e. Xwedê hewcedar e. Nedayî û nehatiye dinê. Tu kes wekî wî tuneye.' } },
  { id: 3, sure: 'Ra’d', ayet: '28',
    arapca: 'أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ',
    meal: { tr: 'Bilin ki kalpler ancak Allah’ı anmakla huzura kavuşur.', en: 'Truly, it is by the remembrance of Allah that hearts find rest.', de: 'Wahrlich, nur durch das Gedenken an Allah finden die Herzen Ruhe.', ar: 'ألا بذكر الله تطمئن القلوب.', ku: 'Zanin, dil tenê bi bîranîna Xwedê re aram dibin.' } },
  { id: 4, sure: 'Bakara', ayet: '286',
    arapca: 'لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا',
    meal: { tr: 'Allah hiçbir kimseye gücünün yeteceğinden fazlasını yüklemez.', en: 'Allah does not burden any soul beyond its capacity.', de: 'Allah bürdet keiner Seele mehr auf, als sie tragen kann.', ar: 'لا يكلّف الله نفساً إلا وسعها.', ku: 'Xwedê ji kêsedî zêdetirê hêza wî bar nakin.' } },
  { id: 5, sure: 'Şura', ayet: '13',
    arapca: 'إِنَّ الدِّينَ عِندَ اللَّهِ الْإِسْلَامُ',
    meal: { tr: 'Şüphesiz Allah katında tek din İslâm’dır.', en: 'Indeed, the religion in the sight of Allah is Islam.', de: 'Wahrlich, die Religion vor Allah ist der Islam.', ar: 'إن الدين عند الله الإسلام.', ku: 'Bêguman ol li ba Xwedê Îslam e.' } },
  { id: 6, sure: 'Zümer', ayet: '53',
    arapca: 'لَا تَقْنَطُوا مِن رَّحْمَةِ اللَّهِ ۚ إِنَّ اللَّهَ يَغْفِرُ الذُّنُوبَ جَمِيعًا',
    meal: { tr: 'Allah’ın rahmetinden ümit kesmeyin. Şüphesiz Allah bütün günahları bağışlar.', en: 'Do not despair of the mercy of Allah. Indeed, Allah forgives all sins.', de: 'Verzweifelt nicht an der Barmherzigkeit Allahs. Wahrlich, Allah vergibt alle Sünden.', ar: 'لا تقنطوا من رحمة الله إن الله يغفر الذنوب جميعاً.', ku: 'Ji dilovanî ya Xwedê bêhêvî nebin. Bêguman Xwedê hemû gunehan dibexşîne.' } },
  { id: 7, sure: 'Fecr', ayet: '27-30',
    arapca: 'يَا أَيَّتُهَا النَّفْسُ الْمُطْمَئِنَّةُ ۝ ارْجِعِي إِلَى رَبِّكِ رَاضِيَةً مَّرْضِيَّةً',
    meal: { tr: 'Ey huzur bulmuş nefis! Razı edici ve razı edilmiş olarak Rabbine dön.', en: 'O tranquil soul! Return to your Lord, well-pleased and well-pleasing.', de: 'Du beruhigte Seele! Kehre zu deinem Herrn zurück, zufrieden und wohlgefällig.', ar: 'يا أيتها النفس المطمئنة ارجعي إلى ربك راضية مرضية.', ku: 'Ey nefşa aram! Razî û têrazîkirî vegeriyê ser Xwedêyê xwe.' } },
  { id: 8, sure: 'Nahl', ayet: '97',
    arapca: 'مَنْ عَمِلَ صَالِحًا مِّن ذَكَرٍ أَوْ أُنثَىٰ وَهُوَ مُؤْمِنٌ فَلَنُحْيِيَنَّهُ حَيَاةً طَيِّبَةً',
    meal: { tr: 'Erkek olsun kadın olsun, mümin olarak iyi amel işleyenlere güzel bir hayat yaşatacağız.', en: 'Whoever does righteousness, whether male or female, while being a believer — We will grant a good life.', de: 'Wer Gutes tut, ob Mann oder Frau, als Gläubiger — dem gewähren Wir ein gutes Leben.', ar: 'من عمل صالحاً من ذكر أو أنثى وهو مؤمن فلنحيينه حياة طيبة.', ku: 'Kî karê baş bike, mê an jî nêr, dema ew bawer be — em ê jê re jiyaneke xweş bidin.' } },
  { id: 9, sure: 'İsra', ayet: '80',
    arapca: 'رَّبِّ أَدْخِلْنِي مُدْخَلَ صِدْقٍ وَأَخْرِجْنِي مُخْرَجَ صِدْقٍ',
    meal: { tr: 'Rabbim! Beni doğru bir girişle girdir, doğru bir çıkışla çıkar.', en: 'My Lord! Let me enter a truthful entrance and exit a truthful exit.', de: 'Mein Herr! Lass mich auf wahrheitsgemäße Weise eintreten und auf wahrheitsgemäße Weise austreten.', ar: 'رب أدخلني مدخل صدق وأخرجني مخرج صدق.', ku: 'Xwedê yê min! Bi ketineke rast têxe û bi derketineke rast derxîne.' } },
  { id: 10, sure: 'Tekasür', ayet: '1-2',
    arapca: 'أَلْهَاكُمُ التَّكَاثُرُ ۝ حَتَّىٰ زُرْتُمُ الْمَقَابِرَ',
    meal: { tr: 'Çoğluk övünmesi sizi o kadar meşgul etti ki kabirleri ziyaretle meşgul oldunuz.', en: 'The mutual rivalry for piling up distracted you, until you visit the graves.', de: 'Die Vielheit lenkte euch ab, so sehr, dass ihr die Gräber besucht.', ar: 'ألهكم التكاثر حتى زرتم المقابر.', ku: 'Pêşbazî ya zêdebûnê we wisa birûskand ku hûn gorrî geriyandin.' } },
];

export const HADISLER = [
  { id: 1, kaynak: 'Buhârî, Îmân 41',
    arapca: 'إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ، وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى',
    meal: { tr: 'Ameller niyetlere göredir. Herkes ne niyet ettiyse onun karşılığını alır.', en: 'Actions are judged by intentions, and everyone gets what he intended.', de: 'Die Taten sind nach den Absichten zu beurteilen, und jedem gebührt, was er beabsichtigte.', ar: 'إنما الأعمال بالنيات وإنما لكل امرئ ما نوى.', ku: 'Kar bi nîyetan tên jimartin, û her kesê tiştê ku nîyet kiriye distîne.' } },
  { id: 2, kaynak: 'Buhârî, Edeb 27',
    arapca: 'لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ',
    meal: { tr: 'Sizden hiçbiriniz, kardeşi için istediğini kendisi için istemedikçe iman etmiş olmaz.', en: 'None of you truly believes until he loves for his brother what he loves for himself.', de: 'Keiner von euch glaubt wirklich, bis er für seinen Bruder liebt, was er für sich selbst liebt.', ar: 'لا يؤمن أحدكم حتى يحب لأخيه ما يحب لنفسه.', ku: 'Tu kes ji we bawer nake heta ji birayê xwe re ew çi ku ji xwe re dixwaze bixwaze.' } },
  { id: 3, kaynak: 'Müslim, Birr 66 / Buhârî, Tevhîd 22',
    arapca: 'مَنْ لَا يَرْحَمُ النَّاسَ لَا يَرْحَمُهُ اللَّهُ',
    meal: { tr: 'İnsanlara merhamet etmeyene Allah da merhamet etmez.', en: 'Whoever shows no mercy to people, Allah shows no mercy to him.', de: 'Wer den Menschen keine Barmherzigkeit zeigt, dem zeigt Allah keine Barmherzigkeit.', ar: 'من لا يرحم الناس لا يرحمه الله.', ku: 'Kî ku ji mirovan re dilovanî nake, Xwedê jî ji wî re dilovanî nake.' } },
  { id: 4, kaynak: 'Tirmizî, Zühd 25',
    arapca: 'كُنْ فِي الدُّنْيَا كَأَنَّكَ غَرِيبٌ أَوْ عَابِرُ سَبِيلٍ',
    meal: { tr: 'Dünyada bir garip ya da bir yolcu gibi ol.', en: 'Be in this world as a stranger or a traveller passing through.', de: 'Sei in dieser Welt wie ein Fremder oder ein Durchreisender.', ar: 'كن في الدنيا كأنك غريب أو عابر سبيل.', ku: 'Di vê cîhanê de wekî biyanî an rêwiyekî bibîn.' } },
  { id: 5, kaynak: 'Tirmizî, Kıyâme 25 / Ebû Dâvûd, Tergîb 44',
    arapca: 'الْكَيِّسُ مَنْ دَانَ نَفْسَهُ وَعَمِلَ لِمَا بَعْدَ الْمَوْتِ',
    meal: { tr: 'Akıllı kişi nefsini hesaba çeken ve ölümden sonrası için çalışandır.', en: 'The wise is he who holds himself to account and works for what comes after death.', de: 'Der Kluge ist, wer sich selbst zur Rechenschaft zieht und für das nach dem Tod wirkt.', ar: 'الكيس من دان نفسه وعمل لما بعد الموت.', ku: 'Kî ji xwe hesab dibe û ji bo piştî mirinê dixebite, ew zana ye.' } },
  { id: 6, kaynak: 'Buhârî, Mevâkîtu’s-Salât 33; Müslim, Birr 116',
    arapca: 'الْمُؤْمِنُ لِلْمُؤْمِنِ كَالْبُنْيَانِ يَشُدُّ بَعْضُهُ بَعْضًا',
    meal: { tr: 'Mümin müminin binası gibidir; bir kısmı diğerini kenetler.', en: 'A believer to a believer is like a building whose parts strengthen one another.', de: 'Der Gläubige ist für den Gläubigen wie ein Bauwerk, dessen Teile einander stützen.', ar: 'المؤمن للمؤمن كالبنيان يشد بعضه بعضاً.', ku: 'Bawer ji bo bawerê wekî avahiyekî ye, hinek bi hinekan re xurt dibin.' } },
  { id: 7, kaynak: 'Ebu Dâvûd, Tıbb 1 / Müslim, Birr 103',
    arapca: 'مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ طَرِيقًا إِلَى الْجَنَّةِ',
    meal: { tr: 'İlim tahsil etmek için yola çıkana Allah cennete giden yolu kolaylaştırır.', en: 'Whoever takes a path seeking knowledge, Allah eases for him a way to Paradise.', de: 'Wer einen Weg zur Suche nach Wissen beschreitet, dem erleichtert Allah einen Weg zum Paradies.', ar: 'من سلك طريقاً يلتمس فيه علماً سهّل الله له طريقاً إلى الجنة.', ku: 'Kî ku di rêya zanîniyê de derkeve, Xwedê rêya bihuştê jê re hêsankirin.' } },
  { id: 8, kaynak: 'İbn Mâce, Ticârât 1',
    arapca: 'طَلَبُ الْحَلَالِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ',
    meal: { tr: 'Helal rızkı aramak her Müslümana farzdır.', en: 'Seeking lawful provision is an obligation upon every Muslim.', de: 'Erlaubtes (halal) Vermögen zu suchen, ist Pflicht für jeden Muslim.', ar: 'طلب الحلال فريضة على كل مسلم.', ku: 'Lêgerîna helalê li ser her muslumanê pêwîst e.' } },
  { id: 9, kaynak: 'Müslim, Tahâret 1',
    arapca: 'الطُّهُورُ شَطْرُ الْإِيمَانِ',
    meal: { tr: 'Temizlik imanın yarısıdır.', en: 'Cleanliness is half of faith.', de: 'Reinlichkeit ist die Hälfte des Glaubens.', ar: 'الطهور شطر الإيمان.', ku: 'Paqîbûn nîvê bawerîyê ye.' } },
  { id: 10, kaynak: 'Tirmizî, Birr 16',
    arapca: 'الرَّاحِمُونَ يَرْحَمُهُمُ الرَّحْمَٰنُ، ارْحَمُوا مَنْ فِي الْأَرْضِ يَرْحَمْكُمْ مَنْ فِي السَّمَاءِ',
    meal: { tr: 'Merhametlilere Rahman merhamet eder. Yerdekilere merhamet edin ki göktekiler size merhamet etsin.', en: 'The merciful are shown mercy by the Most Merciful. Show mercy to those on earth, the One in heaven will show mercy to you.', de: 'Den Barmherzigen wird vom Allerbarmer Barmherzigkeit erwiesen. Seid barmherzig zu den Menschen auf Erden, der im Himmel ist barmherzig zu euch.', ar: 'الراحمون يرحمهم الرحمن، ارحموا من في الأرض يرحمكم من في السماء.', ku: 'Dilovanan dilovanan Rahmê dilerzîne. Di erdê de hûn dilovan bin, êên di ezmênê de êên tê de dilovan in.' } },
  { id: 11, kaynak: 'Buhârî, Îmân 13; Müslim, Îmân 7',
    arapca: 'الإِسْلَامُ أَنْ تَعْبُدَ اللَّهَ وَلَا تُشْرِكَ بِهِ شَيْئًا',
    meal: { tr: 'İslam, Allah’a ibadet edip O’na hiçbir şey ortak koşmaktır.', en: 'Islam is to worship Allah and associate none with Him.', de: 'Islam ist, Allah zu dienen und Ihm nichts beizugesellen.', ar: 'الإسلام أن تعبد الله ولا تشرك به شيئاً.', ku: 'Îslam ew e ku meriv perestina Xwedê bike û tiştekî pê re şerîk neke.' } },
  { id: 12, kaynak: 'Tirmizî, Zühd 11',
    arapca: 'مِنْ حُسْنِ إِسْلَامِ الْمَرْءِ تَرْكُهُ مَا لَا يَعْنِيهِ',
    meal: { tr: 'Kişinin İslam’ının güzelliği, kendisini ilgilendirmeyen şeyi bırakmasıdır.', en: 'Part of a person’s good Islam is leaving what does not concern him.', de: 'Zu einem guten Islam gehört, liegen zu lassen, was einen nicht angeht.', ar: 'من حسن إسلام المرء تركه ما لا يعنيه.', ku: 'Beşek ji Îslama qenc ya meriv terkkirin ya tiştên ku wî nakin e.' } },
  { id: 13, kaynak: 'Buhârî, Îmân 4; Müslim, Îmân 65',
    arapca: 'الْمُسْلِمُ مَنْ سَلِمَ النَّاسُ مِنْ لِسَانِهِ وَيَدِهِ',
    meal: { tr: 'Müslüman, dilinden ve elinden Müslümanların zarar görmediği kimsedir.', en: 'A Muslim is the one from whose tongue and hand the people are safe.', de: 'Ein Muslim ist der, von dessen Zunge und Hand die Menschen sicher sind.', ar: 'المسلم من سلم الناس من لسانه ويده.', ku: 'Musluman ew e ku mirovên ji zimanê wî û destên wî ewle ne.' } },
  { id: 14, kaynak: 'Buhârî, Îmân 11; Müslim, Birr 108',
    arapca: 'يَسِّرُوا وَلَا تُعَسِّرُوا، وَبَشِّرُوا وَلَا تُنَفِّرُوا',
    meal: { tr: 'Kolaylaştırın, zorlaştırmayın; müjdeleyin, nefret ettirmeyin.', en: 'Make things easy, do not make them hard; give glad tidings, do not repel.', de: 'Erleichtert und erschwert nicht; verkündet Frohes und weckt keinen Abscheu.', ar: 'يسّروا ولا تعسّروا، وبشّروا ولا تنفّروا.', ku: 'Hêsankin û ne dijwar kin; mizginî bînin û ne memnûr nekin.' } },
  { id: 15, kaynak: 'Müslim, Îmân 17',
    arapca: 'الدِّينُ النَّصِيحَةُ',
    meal: { tr: 'Din samîmî öğüttür (nasihattir).', en: 'Religion is sincere advice.', de: 'Die Religion ist aufrichtiger Rat.', ar: 'الدين النصيحة.', ku: 'Ol şîret e (pêşniyara dilsoz).' } },
  { id: 16, kaynak: 'Buhârî, Edeb 31; Müslim, Îmân 63',
    arapca: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الْآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ',
    meal: { tr: 'Allah’a ve âhiret gününe iman eden, ya hayır söylesin ya da sussun.', en: 'Whoever believes in Allah and the Last Day, let him speak good or remain silent.', de: 'Wer an Allah und den Jüngsten Tag glaubt, der spreche Gutes oder schweige.', ar: 'من كان يؤمن بالله واليوم الآخر فليقل خيراً أو ليصمت.', ku: 'Kî ku bi Xwedê û roja dawîn bawer be, yan qencê bibêje yan bêdeng bimîne.' } },
  { id: 17, kaynak: 'Buhârî, Edeb 31; Müslim, Îmân 74',
    arapca: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الْآخِرِ فَلْيُكْرِمْ جَارَهُ',
    meal: { tr: 'Allah’a ve âhiret gününe iman eden, komşusuna ikram etsin.', en: 'Whoever believes in Allah and the Last Day, let him be generous to his neighbour.', de: 'Wer an Allah und den Jüngsten Tag glaubt, der ehre seinen Nachbarn.', ar: 'من كان يؤمن بالله واليوم الآخر فليكرم جاره.', ku: 'Kî ku bi Xwedê û roja dawîn bawer be, cîranê xwe bi rêz ve girêbide.' } },
  { id: 18, kaynak: 'Buhârî, Fezâilü’l-Kur’ân 21',
    arapca: 'خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ',
    meal: { tr: 'Sizin en hayırlınız, Kur’an’ı öğrenen ve öğreteninizdir.', en: 'The best of you are those who learn the Qur’an and teach it.', de: 'Der Beste von euch ist, wer den Qur’an lernt und lehrt.', ar: 'خيركم من تعلّم القرآن وعلّمه.', ku: 'Baştirînên we yên ku Quranê hîn dibin û hîn dikin.' } },
  { id: 19, kaynak: 'Buhârî, Îmân 36; Müslim, Musâkat 104',
    arapca: 'أَحَبُّ الْأَعْمَالِ إِلَى اللَّهِ أَدْوَمُهَا وَإِنْ قَلَّ',
    meal: { tr: 'Allah katında amellerin en sevimlisi, az da olsa devamlı olanıdır.', en: 'The most beloved of deeds to Allah are the most constant, even if little.', de: 'Die Allah liebsten Taten sind die beständigsten, auch wenn sie gering sind.', ar: 'أحب الأعمال إلى الله أدومها وإن قلّ.', ku: 'Karên herî nazik ên Xwedê yên herî berdewan in, her çend hindik bin.' } },
  { id: 20, kaynak: 'Müslim, Îmân 105',
    arapca: 'مَنْ دَعَا إِلَى هُدًى كَانَ لَهُ مِنَ الْأَجْرِ مِثْلُ أُجُورِ مَنْ تَبِعَهُ',
    meal: { tr: 'Kim bir hidâyete çağırırsa, tâbi olanların ecri kadar ecir alır.', en: 'Whoever calls to guidance, has a reward like the rewards of those who follow him.', de: 'Wer zur Rechtleitung aufruft, erhält einen Lohn gleich dem derer, die ihm folgen.', ar: 'من دعا إلى هدًى كان له من الأجر مثل أجور من تبعه.', ku: 'Kî ku bangî rêberî yê bikin, wî yê wî wekî yên wî şopandinê kar dikin.' } },
  { id: 21, kaynak: 'Müslim, Zikr 39; Tirmizî, Birr 36',
    arapca: 'وَالْكَلِمَةُ الطَّيِّبَةُ صَدَقَةٌ',
    meal: { tr: 'Güzel söz sadakadır; tebessüm de sadakadır.', en: 'A good word is charity; even a smile is charity.', de: 'Ein gutes Wort ist Almosen; sogar ein Lächeln ist Almosen.', ar: 'والكلمة الطيبة صدقة، وتبسّمك في وجه أخيك صدقة.', ku: 'Peyva qenc alîkarî ye; heta kenînekî jî alîkarî ye.' } },
  { id: 22, kaynak: 'Buhârî, Ezân 32; Müslim, Mesâcid 533',
    arapca: 'مَنْ بَنَى لِلَّهِ مَسْجِدًا بَنَى اللَّهُ لَهُ بَيْتًا فِي الْجَنَّةِ',
    meal: { tr: 'Kim Allah için bir mescit yaparsa, Allah ona cennette bir ev yapar.', en: 'Whoever builds a mosque for Allah, Allah builds for him a house in Paradise.', de: 'Wer für Allah eine Moschee baut, dem baut Allah ein Haus im Paradies.', ar: 'من بنى لله مسجداً بنى الله له بيتاً في الجنة.', ku: 'Kî ku ji bo Xwedê mizgeftekê ava bike, Xwedê jê re di bihuştê de malekî ava dike.' } },
  { id: 23, kaynak: 'Müslim, Birr 55',
    arapca: 'مَنْ لَا يَشْكُرُ النَّاسَ لَا يَشْكُرُ اللَّهَ',
    meal: { tr: 'İnsanlara şükretmeyen, Allah’a şükretmiş olmaz.', en: 'Whoever does not thank people, does not thank Allah.', de: 'Wer den Menschen nicht dankt, dankt Allah nicht.', ar: 'من لا يشكر الناس لا يشكر الله.', ku: 'Kî ku ji mirovan sipasiyê na kîşîne, ji Xwedê jî sipasiyê nake.' } },
  { id: 24, kaynak: 'Müslim, Fezâil 98; Ebu Dâvûd, Edeb 142',
    arapca: 'الْجَنَّةُ تَحْتَ أَقْدَامِ الْأُمَّهَاتِ',
    meal: { tr: 'Cennet annelerin ayakları altındadır.', en: 'Paradise lies beneath the feet of mothers.', de: 'Das Paradies liegt zu den Füßen der Mütter.', ar: 'الجنة تحت أقدام الأمهات.', ku: 'Bihuşt di binê lingên dêyan de ye.' } },
  { id: 25, kaynak: 'Müslim, Îmân 130',
    arapca: 'مَنْ دَلَّ عَلَىٰ خَيْرٍ فَلَهُ مِثْلُ أَجْرِ فَاعِلِهِ',
    meal: { tr: 'Hayra delalet eden, o hayrı işleyenin ecri kadar ecir alır.', en: 'Whoever guides to good gets a reward like the one who does it.', de: 'Wer zum Guten leitet, erhält Lohn wie der Handelnde.' } },
  { id: 26, kaynak: 'Müslim, Birr 58',
    arapca: 'مَنْ نَفَّسَ عَنْ مُؤْمِنٍ كُرْبَةً نَفَّسَ اللَّهُ عَنْهُ كُرْبَةً مِنْ كُرَبِ يَوْمِ الْقِيَامَةِ',
    meal: { tr: 'Müminin bir sıkıntısını giderene Allah kıyamet günü sıkıntılarından birini giderir.', en: 'Whoever relieves the hardship of a believer, Allah relieves one of his hardships on Judgment Day.', de: 'Wer die Not eines Gläubigen lindert, dem lindert Allah am Jüngsten Tag eine seiner Nöten.' } },
  { id: 27, kaynak: 'Müslim, Libâs 91',
    arapca: 'إِنَّ اللَّهَ جَمِيلٌ يُحِبُّ الْجَمَالَ',
    meal: { tr: 'Allah güzeldir ve güzeli sever.', en: 'Allah is beautiful and loves beauty.', de: 'Allah ist schön und liebt das Schöne.' } },
  { id: 28, kaynak: 'Müslim, Kader 34',
    arapca: 'الْمُؤْمِنُ الْقَوِيُّ خَيْرٌ وَأَحَبُّ إِلَى اللَّهِ مِنَ الْمُؤْمِنِ الضَّعِيفِ',
    meal: { tr: 'Kuvvetli mümin, zayıf müminden Allah katında daha hayırlı ve sevimlidir.', en: 'The strong believer is better and more beloved to Allah than the weak believer.', de: 'Der starke Gläubige ist bei Allah besser und lieber als der schwache.' } },
  { id: 29, kaynak: 'Buhârî, Mezâlim 3',
    arapca: 'انْصُرْ أَخَاكَ ظَالِمًا أَوْ مَظْلُومًا',
    meal: { tr: 'Kardeşine yardım et; ister zalim ister mazlum olsa.', en: 'Help your brother, whether he is the oppressor or the oppressed.', de: 'Hilf deinem Bruder, ob er Unrecht tut oder leidet.' } },
  { id: 30, kaynak: 'Buhârî, Edeb 76',
    arapca: 'لَا تَغْضَبْ',
    meal: { tr: 'Öfkelenme!', en: 'Do not get angry!', de: 'Werde nicht zornig!' } },
  { id: 31, kaynak: 'Buhârî, Edeb 31; Müslim, Îmân 73',
    arapca: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الْآخِرِ فَلْيُكْرِمْ ضَيْفَهُ',
    meal: { tr: 'Allah ve âhiret gününe iman eden, misafirine ikram etsin.', en: 'Whoever believes in Allah and the Last Day, let him honour his guest.', de: 'Wer an Allah und den Jüngsten Tag glaubt, der ehre seinen Gast.' } },
  { id: 32, kaynak: 'Buhârî, Edeb 62; Müslim, Birr 120',
    arapca: 'لَا يَحِلُّ لِمُسْلِمٍ أَنْ يَهْجُرَ أَخَاهُ فَوْقَ ثَلَاثٍ',
    meal: { tr: 'Müslümanın kardeşiyle üç günden fazla küs durması helal değildir.', en: 'It is not lawful for a Muslim to shun his brother for more than three days.', de: 'Es ist einem Muslim nicht erlaubt, seinen Bruder länger als drei Tage zu meiden.' } },
  { id: 33, kaynak: 'Buhârî, Mezâlim 3; Müslim, Birr 58',
    arapca: 'الْمُسْلِمُ أَخُو الْمُسْلِمِ، لَا يَظْلِمُهُ وَلَا يَخْذُلُهُ وَلَا يَكْذِبُهُ',
    meal: { tr: 'Müslüman müslümanın kardeşidir; ona zulmetmez, onu yüzüstü bırakmaz, yalan söylemez.', en: 'A Muslim is the brother of a Muslim; he does not wrong him, fail him, or lie to him.', de: 'Ein Muslim ist der Bruder des Muslims; er tut ihm kein Unrecht, überlässt ihn nicht und belügt ihn nicht.' } },
  { id: 34, kaynak: 'Buhârî, İlim 15; Müslim, Musâkirîn 268',
    arapca: 'لَا حَسَدَ إِلَّا فِي اثْنَتَيْنِ',
    meal: { tr: 'Gıbta ancak iki şeyde hoştur: Kur’an’ı öğrenip öğreten ve malını hayır yolunda harcayan.', en: 'Envy is acceptable only in two: one who learns and teaches the Qur’an, and one who gives wealth in charity.', de: 'Missgunst ist nur in zwei Dingen gut: wer den Qur’an lernt und lehrt, und wer seinen Besitz spendet.' } },
  { id: 35, kaynak: 'Buhârî, Cenâiz 2; Müslim, Cenâiz 45',
    arapca: 'مَنْ تَبِعَ جَنَازَةً فَلَهُ قِيرَاطٌ، وَمَنْ صَلَّى عَلَيْهَا فَلَهُ قِيرَاطَانِ',
    meal: { tr: 'Cenazeyi takip edene bir kırat, namazını kılana iki kırat sevap vardır.', en: 'Whoever follows a funeral earns one qirat, and whoever prays over it earns two.', de: 'Wer einem Begräbnis folgt, erhält einen Qirat, und wer darüber betet, zwei.' } },
  { id: 36, kaynak: 'Müslim, Salavât 10',
    arapca: 'مَنْ صَلَّى عَلَيَّ صَلَاةً صَلَّى اللَّهُ عَلَيْهِ بِهَا عَشْرًا',
    meal: { tr: 'Bana bir salavat okuyana Allah on salavat (rahmet) okur.', en: 'Whoever sends one blessing upon me, Allah sends ten blessings upon him.', de: 'Wer mir einen Segen sendet, dem sendet Allah zehn Segen.' } },
];

export const EVLIYA_SOZLERI = [
  // — Şeyh Seyda İzzeddin El-Urfevî Hz. (öncelikli) —
  { id: 1, sahibi: { tr: 'Şeyh Seyda İzzeddin El-Urfevî', en: 'Sheikh Seyda Izzeddin al-Urfavi', de: 'Scheich Seyda Izzeddin al-Urfavi', ar: 'الشيخ سيدا عز الدين الأرفي', ku: 'Şêx Seyda Îzeddîn El-Urfavî' },
    meal: { tr: 'Asıl hüner; halkın içinde olduğu halde Hak’tan bir an bile ayrılmamak ve istikameti bozmamaktır.', en: 'The true skill is to remain among people yet never part from the Truth for an instant, and to keep one’s path straight.', de: 'Die wahre Kunst ist, inmitten der Menschen zu sein und doch keinen Augenblick von der Wahrheit zu weichen und den geraden Weg zu wahren.', ar: 'الحذق الحقيقي هو أن تكون بين الخلق ولا تفارق الحق طرفة عين، وأن تستقيم.', ku: 'Hûnera rast ew e ku meriv di nav gel de be û qe ji Rastiyê duçav negire û rê xwe rast bigire.' } },
  { id: 2, sahibi: { tr: 'Şeyh Seyda İzzeddin El-Urfevî', en: 'Sheikh Seyda Izzeddin al-Urfavi', de: 'Scheich Seyda Izzeddin al-Urfavi', ar: 'الشيخ سيدا عز الدين الأرفي', ku: 'Şêx Seyda Îzeddîn El-Urfavî' },
    meal: { tr: 'Dostların meclisi cennet bağıdır; orada açılan muhabbet gülü hiç solmaz.', en: 'The gathering of friends is a garden of paradise; the rose of love that opens there never fades.', de: 'Die Versammlung der Freunde ist ein Garten des Paradieses; die Rose der Liebe, die dort erblüht, verwelkt nie.', ar: 'مجلس الأحباب روضة من رياض الجنة، وورد المحبة فيه لا يذبل.', ku: 'Mecrova hevalan baxçeyekî bihuştê ye; gula hezkirina ku li vir vedibe qet hişk nabe.' } },
  { id: 3, sahibi: { tr: 'Şeyh Seyda İzzeddin El-Urfevî', en: 'Sheikh Seyda Izzeddin al-Urfavi', de: 'Scheich Seyda Izzeddin al-Urfavi', ar: 'الشيخ سيدا عز الدين الأرفي', ku: 'Şêx Seyda Îzeddîn El-Urfavî' },
    meal: { tr: 'Allah dostlarının meclisleri, insanı dünyadan alıp âhirete yaklaştıran, kalbe Allah sevgisini yerleştiren yerlerdir.', en: 'The gatherings of Allah’s friends lift a person from this world toward the Hereafter and plant the love of Allah in the heart.', de: 'Die Versammlungen der Freunde Allahs heben den Menschen von der Welt zur jenseitigen Heimat und pflanzen die Liebe Allahs ins Herz.', ar: 'مجالس أولياء الله ترفع العبد من الدنيا إلى الآخرة وتغرز محبة الله في القلب.', ku: 'Mecrevayên dostên Xwedê merivê ji vê dinyayê bilind dikin û evîna Xwedê di dil de dicînin.' } },
  { id: 4, sahibi: { tr: 'Şeyh Seyda İzzeddin El-Urfevî', en: 'Sheikh Seyda Izzeddin al-Urfavi', de: 'Scheich Seyda Izzeddin al-Urfavi', ar: 'الشيخ سيدا عز الدين الأرفي', ku: 'Şêx Seyda Îzeddîn El-Urfavî' },
    meal: { tr: 'Hak yolunda gitmek bir memleketten diğerine gitmek gibidir; yollar inişli-yokuşlu, düz-eğri olur; sabırla yürünür.', en: 'Walking the path of Truth is like travelling from land to land; roads rise and fall, are straight and crooked; one walks them with patience.', de: 'Auf dem Pfad der Wahrheit zu gehen ist wie von Land zu Land zu ziehen; Wege steigen und fallen, mal gerade mal krumm; man geht sie in Geduld.', ar: 'السير في طريق الحق كالسفر من بلد إلى بلد؛ طرق صعود وهبوط، واستقامة واعوجاج، يُسار بالصبر.', ku: 'Rêya Rastiyê wekî rêwetiya ji welatekî hîna yê din e; rê hilkirî û dadişkî, rast û xwar hene; bi hewqê tê gerîn.' } },
  { id: 5, sahibi: { tr: 'Şeyh Seyda İzzeddin El-Urfevî', en: 'Sheikh Seyda Izzeddin al-Urfavi', de: 'Scheich Seyda Izzeddin al-Urfavi', ar: 'الشيخ سيدا عز الدين الأرفي', ku: 'Şêx Seyda Îzeddîn El-Urfavî' },
    meal: { tr: 'Allah bir kulu sevdiğinde onu dostlarına gönderir; kalbini onlarla meşgul kılar.', en: 'When Allah loves a servant, He sends him to His friends; He keeps his heart busy with them.', de: 'Wenn Allah einen Diener liebt, schickt Er ihn zu Seinen Freunden; Er beschäftigt sein Herz mit ihnen.', ar: 'إذا أحب الله عبداً أرسله إلى أوليائه، واشتغل قلبه بهم.', ku: 'Gava Xwedê ji bendeyekî hez bike ew ber bi dostên xwe ve dişîne; dilê wî bi wan re mijûl dike.' } },
  { id: 6, sahibi: { tr: 'Şeyh Seyda İzzeddin El-Urfevî', en: 'Sheikh Seyda Izzeddin al-Urfavi', de: 'Scheich Seyda Izzeddin al-Urfavi', ar: 'الشيخ سيدا عز الدين الأرفي', ku: 'Şêx Seyda Îzeddîn El-Urfavî' },
    meal: { tr: 'Her bir nasihati bir külçe altın değerindedir; dileyen alır, dileyen geçer gider.', en: 'Every counsel of his is worth an ingot of gold; whoever wills takes it, whoever wills passes by.', de: 'Jede seiner Ermahnungen ist einen Barren Gold wert; wer will, nimmt sie, wer will, geht vorbei.', ar: 'كل نصيحة منه تساوي سبيكة ذهب؛ من شاء أخذ، ومن شاء مضى.', ku: 'Her şîretekî wî wekî zêreyekî zêrê ye; kî bixwaze digire, kî bixwaze derbas dibe.' } },
  { id: 7, sahibi: { tr: 'Şeyh Seyda İzzeddin El-Urfevî', en: 'Sheikh Seyda Izzeddin al-Urfavi', de: 'Scheich Seyda Izzeddin al-Urfavi', ar: 'الشيخ سيدا عز الدين الأرفي', ku: 'Şêx Seyda Îzeddîn El-Urfavî' },
    meal: { tr: 'İbadet kalbe huzur verir; hayatın her alanında insana yol gösterir.', en: 'Worship grants the heart peace; it guides a person in every sphere of life.', de: 'Anbetung schenkt dem Herz Ruhe; sie weist den Menschen in allen Bereichen des Lebens.', ar: 'العبادة تطمئن القلب وتهدي المرء في كل أحوال حياته.', ku: 'Perestî dilê hewşt dike û merivê di her warên jiyanê de rê nîşan dike.' } },
  { id: 8, sahibi: { tr: 'Şeyh Seyda İzzeddin El-Urfevî', en: 'Sheikh Seyda Izzeddin al-Urfavi', de: 'Scheich Seyda Izzeddin al-Urfavi', ar: 'الشيخ سيدا عز الدين الأرفي', ku: 'Şêx Seyda Îzeddîn El-Urfavî' },
    meal: { tr: 'Zayıf kalpleri Allah dostlarının sözleri ve güzel halleri kuvvetlendirir; bozulan maneviyatı düzeltir.', en: 'The words and noble states of Allah’s friends strengthen weak hearts and mend broken spirituality.', de: 'Die Worte und edlen Zustände der Freunde Allahs stärken schwache Herzen und richten verdorbene Spiritualität.', ar: 'كلمات وأحوال أولياء الله تقوي القلوب الضعيفة وتصلح ما فسد من الروح.', ku: 'Peyv û halên baş ên dostên Xwedê dilên lawaz xurt dikin û ruhê xirab rast dikin.' } },
  // — Diğer evliyaullah —
  { id: 9, sahibi: { tr: 'İmam Gazâlî', en: 'Imam al-Ghazali', de: 'Imam al-Ghazali', ar: 'الإمام الغزالي', ku: 'Îmamê Gazalî' },
    meal: { tr: 'İlim amelsiz olmaz, amel ilimsiz olmaz; ikisi de kâmil olursa kemal bulunur.', en: 'Knowledge is not without action, nor action without knowledge; perfection comes when both are complete.', de: 'Wissen ohne Handeln gibt es nicht, noch Handeln ohne Wissen; Vollkommenheit entsteht, wenn beide zusammenkommen.', ar: 'لا علم بلا عمل ولا عمل بلا علم، وإذا كمل الأمران حصل الكمال.', ku: 'Zanîn bê karan nîn e, kar bê zanîn jî nîn e; dema herdu têk bûn, kamilîtî peyde dibin.' } },
  { id: 10, sahibi: { tr: 'Mevlânâ Celâleddîn-i Rûmî', en: 'Rumi', de: 'Rumi', ar: 'جلال الدين الرومي', ku: 'Mewlana Celaledînê Rûmî' },
    meal: { tr: 'Ya olduğun gibi görün, ya göründüğün gibi ol.', en: 'Either appear as you are, or be as you appear.', de: 'Entscheide dich: sei, wie du erscheinst, oder erscheine, wie du bist.', ar: 'إما أن تظهر كما أنت، أو أن تكون كما تظهر.', ku: 'An wekî ku tu yî xuya bike, an jî wekî ku xuya dibî bibe.' } },
  { id: 11, sahibi: { tr: 'Abdulkâdir Geylânî', en: 'Abd al-Qadir al-Jilani', de: 'Abd al-Qadir al-Dschilani', ar: 'عبد القادر الجيلاني', ku: 'Ebdulqadirê Geylanî' },
    meal: { tr: 'İlim giyinenin elbisesi, amel onun süsüdür.', en: 'Knowledge is the garment of the knowing, and action their ornament.', de: 'Wissen ist das Gewand des Wissenden, und Handeln sein Schmuck.', ar: 'العلم لباس العالِم والعمل زينته.', ku: 'Zanin libasê zana ye, kar jî sêlê wî ye.' } },
  { id: 12, sahibi: { tr: 'İmam Rabbânî', en: 'Imam Rabbani', de: 'Imam Rabbani', ar: 'الإمام الرباني', ku: 'Îmamê Rabbânî' },
    meal: { tr: 'Dünya sevgisi bütün kötülüklerin anasıdır.', en: 'Love of this world is the root of all wrongdoing.', de: 'Die Liebe zur Welt ist die Wurzel alles Schlechten.', ar: 'حب الدنيا رأس كل خطيئة.', ku: 'Hezkirina dinyayê koka hemû xerabîyan e.' } },
  { id: 13, sahibi: { tr: 'Yunus Emre', en: 'Yunus Emre', de: 'Yunus Emre', ar: 'يونس إمره', ku: 'Yûnusê Emre' },
    meal: { tr: 'Sevelim, sevilelim; dünya kimseye kalmaz.', en: 'Let us love and be loved; the world is left to none.', de: 'Lasst uns lieben und geliebt werden; die Welt bleibt bei niemandem.', ar: 'نحب ونُحب، فالدنيا لا تبقى لأحد.', ku: 'Hez bikîn, bên hêzkirin; dinya li kê neserrîte.' } },
  { id: 14, sahibi: { tr: 'İbn Atâullah İskenderî', en: 'Ibn Ata Allah', de: 'Ibn Ata Allah', ar: 'ابن عطاء الله السكندري', ku: 'Îbn Ataullahê Îskenderî' },
    meal: { tr: 'Belki de O seni terk etmedi, sen O’nu terk ettin.', en: 'Perhaps He did not abandon you; you abandoned Him.', de: 'Vielleicht hat Er dich nicht verlassen; du hast Ihn verlassen.', ar: 'لعله ما تركك، بل أنت تركته.', ku: 'Dibe ku wî te nehijiştibe, tu yî wî hiştiye.' } },
  { id: 15, sahibi: { tr: 'Şâh-ı Nakşibend', en: 'Bahauddin Naqshband', de: 'Bahauddin Naqschband', ar: 'بهاء الدين النقشبند', ku: 'Şahê Nxşbendî' },
    meal: { tr: 'Dilinde Allah, kalbinde Allah, elinde Allah ile ol.', en: 'Keep Allah on your tongue, in your heart, and in your hands.', de: 'Trage Allah auf der Zunge, im Herzen und in den Händen.', ar: 'احفظ الله في لسانك وقلبك ويدك.', ku: 'Xwedê li ser zimanê xwe, di dilê xwe de û di destên xwe de bigire.' } },
  { id: 16, sahibi: { tr: 'Ebû Hasan eş-Şâzelî', en: 'Abu al-Hasan al-Shadhili', de: 'Abu l-Hasan asch-Schadhili', ar: 'أبو الحسن الشاذلي', ku: 'Ebû Hesenê Şazelî' },
    meal: { tr: 'Allah’tan başkasına meyleden huzuru bulamaz.', en: 'Whoever leans toward other than Allah finds no peace.', de: 'Wer sich anderem als Allah zuneigt, findet keine Ruhe.', ar: 'من مال إلى غير الله لم يجد الطمأنينة.', ku: 'Kî ku ji pêve Xwedê ve xwe bidinî têdegirtin, aramî nabît.' } },
  { id: 17, sahibi: { tr: 'İmam Şâfiî', en: 'Imam al-Shafii', de: 'Imam asch-Schafii', ar: 'الإمام الشافعي', ku: 'Îmamê Şafiî' },
    meal: { tr: 'İlim bir hazinedir; onun anahtarı sormaktır.', en: 'Knowledge is a treasure, and its key is asking.', de: 'Wissen ist ein Schatz, und sein Schlüssel ist das Fragen.', ar: 'العلم كنز ومفتاحه السؤال.', ku: 'Zanîn xezîne ye; miftîha wî pirsîn e.' } },
  { id: 18, sahibi: { tr: 'Şeyh Şâmil', en: 'Sheikh Shamil', de: 'Scheich Schamil', ar: 'الشيخ شامل', ku: 'Şêx Şamil' },
    meal: { tr: 'Sabır, en zaruri azıktır; onu yitiren yolunu yitirir.', en: 'Patience is the most necessary provision; whoever loses it loses the way.', de: 'Geduld ist die notwendigste Wegzehrung; wer sie verliert, verliert den Weg.', ar: 'الصبر زاد لا غنى عنه، ومن فقده ضلّ طريقه.', ku: 'Hewq herî pêwendiya rê ye; kî wî winda bike rê wî winda dike.' } },
  { id: 19, sahibi: { tr: 'Bâyezîd-i Bistâmî', en: 'Bayazid Bistami', de: 'Bayazid Bistami', ar: 'بايزيد البسطامي', ku: 'Beyazîdê Bîstamî' },
    meal: { tr: 'Seni sevmekten korkmam, çünkü kalbim Seninle mest olmuştur.', en: 'I fear not loving You, for my heart is lost in You.', de: 'Ich fürchte mich nicht, Dich zu lieben, denn mein Herz versinkt in Dir.', ar: 'لا أخاف من محبتك، لأن قلبي قد فُتن بك.', ku: 'Ez ji hezkirina te natirimên, ji ber ku dilê min bi te reserde maye.' } },
  { id: 20, sahibi: { tr: 'Ârif Rüveylî', en: 'Arif er-Rivayli', de: 'Arif er-Rivayli', ar: 'عارف الرّويلي', ku: 'Arifê Rûveyîî' },
    meal: { tr: 'Az yiyen, az uyuyan ve az konuşan sırrın sahibi olur.', en: 'Who eats, sleeps and speaks little becomes the keeper of secrets.', de: 'Wer wenig isst, wenig schläft und wenig spricht, wird zum Hüter der Geheimnisse.', ar: 'من قلّ طعامه وقلّ نومه وقلّ كلامه صار حافظاً للسرّ.', ku: 'Kî kêm bixwe, kêm bizêistê, kêm biaxîf, dibe xwediyê veşartî.' } },
  { id: 21, sahibi: { tr: 'Hz. Ali', en: 'Ali ibn Abi Talib', de: 'Ali ibn Abi Talib', ar: 'علي بن أبي طالب', ku: 'Hz. Elî' },
    meal: { tr: 'Nefsinin arzusunun peşinden koşma; ölüm için hazırlan.', en: 'Do not chase the desire of your soul; prepare for death.', de: 'Jage nicht der Begierde nach; bereite dich auf den Tod vor.', ar: 'لا تتبع هوى النفس، وتجهّز للموت.', ku: 'Pê teşqî ya nefşê neke; ji bo mirinê amade bibe.' } },
  { id: 22, sahibi: { tr: 'Hz. Ebû Bekir', en: 'Abu Bakr al-Siddiq', de: 'Abu Bakr as-Siddiq', ar: 'أبو بكر الصديق', ku: 'Hz. Ebûbekir' },
    meal: { tr: 'Hiçbir nimet şükürden daha layık bir taşıyıcı bulamaz.', en: 'No blessing finds a worthier carrier than gratitude.', de: 'Keine Gnade findet einen würdigeren Träger als den Dank.', ar: 'ما نعم وَجَدَت حاملاً أحقّ به من الشكر.', ku: 'Tu nîmet ji sipasiyê bêhtir hilgirê guncav qet nedît.' } },
  { id: 23, sahibi: { tr: 'Hasan el-Basrî', en: 'Hasan al-Basri', de: 'Hasan al-Basri', ar: 'الحسن البصري', ku: 'Hesenê Basrî' },
    meal: { tr: 'Ölüm için nasihat dinleyenin, dünyanın aldatıcısı ona tesir etmez.', en: 'Whoever listens to the counsel of death is not deceived by the allure of the world.', de: 'Wer auf den Rat des Todes hört, wird vom Schein der Welt nicht getäuscht.', ar: 'من وعظ بالموت لم يغره زخرف الدنيا.', ku: 'Kî ku bi nasîhata mirinê bibihîze, xemgêlê dinyayê nace wî.' } },
  { id: 24, sahibi: { tr: 'İmam Mâlik', en: 'Imam Malik', de: 'Imam Malik', ar: 'الإمام مالك', ku: 'Îmamê Malîk' },
    meal: { tr: 'İlim çarşısına giren herkes mutlaka bir paye sahip çıkar; ya çok ya az.', en: 'Whoever enters the market of knowledge leaves with a share, whether much or little.', de: 'Wer den Markt des Wissens betritt, geht mit einem Anteil, viel oder wenig.', ar: 'من دخل سوق العلم خرج بنصيب، إمّا كثيراً أو قليلاً.', ku: 'Kî ku bazirganiya zanînê bike, bêmaver parek distîne; pir yan jî hindik.' } },
  { id: 25, sahibi: { tr: 'Cüneyd-i Bağdâdî', en: 'Junayd al-Baghdadi', de: 'Dschunaid al-Baghdadi' },
    meal: { tr: 'Kulluğun esası Kur’an’a uymak, sünnete tabi olmak ve helâl lokma yemektir.', en: 'The basis of servitude is following the Qur’an, the Sunnah, and eating lawful food.', de: 'Die Grundlage des Dienens ist, dem Qur’an und der Sunnah zu folgen und Erlaubtes zu essen.' } },
  { id: 26, sahibi: { tr: 'Fudayl bin İyâz', en: 'Fudayl ibn Iyad', de: 'Fudayl ibn Iyad' },
    meal: { tr: 'İnsanların en âlimi Allah’ı bulan; en âbidi nefsiyle savaşan olandır.', en: 'The most learned is one who finds Allah; the most devout is one who fights his ego.', de: 'Der Gelehrteste ist, wer Allah findet; der Andächtigste ist, wer sein Ego bekämpft.' } },
  { id: 27, sahibi: { tr: 'İbrahim Edhem', en: 'Ibrahim ibn Adham', de: 'Ibrahim ibn Adham' },
    meal: { tr: 'Ârif kalbiyle Rabbi, gözüyle nimeti görür; dünya âhirete perde olmasın.', en: 'The gnostic sees his Lord with the heart and His bounty with the eye; let not the world veil the Hereafter.', de: 'Der Kenner sieht seinen Herrn im Herzen und seine Gabe im Auge; die Welt verhülle nicht das Jenseits.' } },
  { id: 28, sahibi: { tr: 'Râbia el-Adeviyye', en: 'Rabia al-Adawiyya', de: 'Rabia al-Adawiyya' },
    meal: { tr: 'Ey Allahım! Yalnız Senin rızân için taparım; ateşinden korktuğum veya cennetini istediğimden değil.', en: 'O Allah! I worship You for Your pleasure alone, not from fear of fire or desire for paradise.', de: 'O Allah! Ich bete Dich allein um Deines Wohlgefallens willen, nicht aus Furcht vor dem Feuer oder Verlangen nach dem Paradies.' } },
  { id: 29, sahibi: { tr: 'Serrî es-Sakatî', en: 'Sari as-Saqati', de: 'Sari as-Saqati' },
    meal: { tr: 'Tasavvuf; eldekilerle yetinmek, elinde olmayana talip olmamaktır.', en: 'Sufism is to be content with what one has and not to pursue what one lacks.', de: 'Sufismus ist, mit dem Vorhandenen zufrieden zu sein und das Fehlende nicht zu begehren.' } },
  { id: 30, sahibi: { tr: 'Şiblî', en: 'Abu Bakr al-Shibli', de: 'Abu Bakr al-Schibli' },
    meal: { tr: 'Marifet, ezelî olandan gayrısını kabullenmemektir.', en: 'Gnosis is to accept nothing but the Eternal.', de: 'Gnosis ist, nichts als das Ewige anzunehmen.' } },
  { id: 31, sahibi: { tr: 'Hâris el-Muhâsibî', en: 'Al-Muhasibi', de: 'Al-Muhasibi' },
    meal: { tr: 'İhlâs, amelde kazanç gözetmemektir.', en: 'Sincerity is to seek no gain in deeds.', de: 'Aufrichtigkeit ist, in Taten keinen Gewinn zu suchen.' } },
  { id: 32, sahibi: { tr: 'İmam Ebû Hanîfe', en: 'Imam Abu Hanifa', de: 'Imam Abu Hanifa' },
    meal: { tr: 'İlimsiz fıkıh olmaz; fıkıhsız amel kâmil olmaz.', en: 'Without knowledge there is no jurisprudence; without jurisprudence no deed is perfect.', de: 'Ohne Wissen kein Fiqh; ohne Fiqh keine vollkommene Tat.' } },
  { id: 33, sahibi: { tr: 'Sehl et-Tüsterî', en: 'Sahl at-Tustari', de: 'Sahl at-Tustari' },
    meal: { tr: 'Mürid, nefsinin hevâsına uymayıp Hakk’a teslim olandır.', en: 'The seeker does not follow the whims of his ego but surrenders to the Truth.', de: 'Der Sucher folgt nicht dem Ego, sondern ergibt sich der Wahrheit.' } },
  { id: 34, sahibi: { tr: 'Abdülhâlık Gucdüvânî', en: 'Abd al-Khaliq Ghujduvani', de: 'Abd al-Chaliq Ghujduvani' },
    meal: { tr: 'Dilini muhafaza et; harama bakma; lüzumsuz laftan kaçın.', en: 'Guard your tongue; do not look at the forbidden; avoid idle talk.', de: 'Hüte deine Zunge; schau nichts Verbotenes; meide leeres Gerede.' } },
  { id: 35, sahibi: { tr: 'Mevlânâ Hâlid-i Bağdâdî', en: 'Mawlana Khalid al-Baghdadi', de: 'Mawlana Khalid al-Baghdadi' },
    meal: { tr: 'Kalb zikirle mamur olursa, dünya darlıkları ona tesir etmez.', en: 'When the heart is built by remembrance, the hardships of the world do not affect it.', de: 'Ist das Herz durch Gedenken gebaut, berühren es die Nöte der Welt nicht.' } },
  { id: 36, sahibi: { tr: 'Ebû Bekir el-Kettânî', en: 'Abu Bakr al-Kattani', de: 'Abu Bakr al-Kattani' },
    meal: { tr: 'Tasavvuf edeptir; edepten nasibini alan, nasibini alır.', en: 'Sufism is good manners; whoever takes a share of adab takes his share.', de: 'Sufismus ist guter Anstand; wer Anstand hat, hat seinen Anteil.' } },
];