workflows:
  ios-capacitor-workflow:
    name: HudaAPP iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: latest
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: | 
          npm install
      - name: Build web assets
        script: | 
          npm run build
      - name: Capacitor Sync iOS
        script: | 
          npx cap sync ios
    artifacts:
      - ios/App/build/Outputs/APK/*.ipa
      - build/exported/*.ipa
