workflows:
  ios-capacitor-workflow:
    name: HudaAPP iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: latest
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: | 
          npm install
          npm install @capacitor/ios
      - name: Build web assets
        script: | 
          npm run build
      - name: Capacitor Sync iOS
        script: | 
          npx cap sync ios
      - name: Build Unsigned iOS Application
        script: | 
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Debug -sdk iphoneos CODE_SIGNING_ALLOWED=NO OBJROOT=$PWD/build SYMROOT=$PWD/build
          mkdir -p $PWD/build/Payload
          cp -r $PWD/build/Debug-iphoneos/App.app $PWD/build/Payload
          cd $PWD/build
          zip -qr HudaAPP.ipa Payload
    artifacts:
      - ios/App/build/*.ipa
